language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
  allow_failures:
    - python: 3.8-dev

install:
  - pip install ptr

script:
    - ptr

notifications:
  irc:
    channels:
      - "chat.freenode.net#exabgp"

cache:
    directories:
        - $HOME/.cache/pip
