language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
    - python: nightly
  allow_failures:
    - python: 3.8-dev
    - python: nightly

install:
  - pip install ptr black coverage flake8 mypy

script:
    - ptr --venv $VIRTUAL_ENV --error-on-warnings

notifications:
  irc:
    channels:
      - "chat.freenode.net#exabgp"

cache:
    directories:
        - $HOME/.cache/pip
